FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
    libudev-dev:arm64 \
    libwayland-dev:arm64 \
    libxkbcommon-dev:arm64 \
    libfontconfig1-dev:arm64 \
    libasound2-dev:arm64 \
    libxcb-xfixes0-dev:arm64 \
    libxcb-shape0-dev:arm64 \
    libx11-dev:arm64
